from utilites.base_page import Basepage
from selenium.webdriver.common.by import By
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.support.select import Select
class Signuppage(Basepage):
    MRS=(By.XPATH,"//input[@id='id_gender2']")
    Password=(By.XPATH,"//input[@id='password']")
    Days=(By.XPATH,"//select[@id='days']")
    Month=(By.XPATH,"//select[@id='months']")
    Year=(By.XPATH,"//select[@id='years']")
    first_name=(By.XPATH,"//input[@id='first_name']")
    lastname=(By.XPATH,"//input[@id='last_name']")
    company=(By.XPATH,"//input[@id='company']")
    checkbox=(By.XPATH,"//input[@id='newsletter']")
    address=(By.XPATH,"//input[@id='address1']")
    address2=(By.XPATH,"//input[@id='address2']")
    country=(By.XPATH,"//select[@id='country']")
    state=(By.XPATH,"//input[@id='state']")
    city=(By.XPATH,"//input[@id='city']")
    zip_code=(By.XPATH,"//input[@id='zipcode']")
    NUMBER=(By.XPATH,"//input[@id='mobile_number']")
    create_acnt=(By.XPATH,"//button[normalize-space()='Create Account']")


    def signup2(self):
        self.click(self.MRS)
        self.type(self.Password,"ASMIT123")
        days=self.wait.until(EC.presence_of_element_located(self.Days))
        select=Select(days)
        select.select_by_visible_text("3")
        months=self.wait.until(EC.presence_of_element_located(self.Month))
        select2=Select(months)
        select2.select_by_visible_text("July")
        year=self.wait.until(EC.presence_of_element_located(self.Year))
        select3=Select(year)
        select3.select_by_visible_text("2014")
        self.click(self.checkbox)
        self.type(self.first_name,"asmi")
        self.type(self.lastname,"kuma")
        self.type(self.company,"pornhub")
        self.type(self.address,"MIG44-16/98 BBA COLO")
        self.type(self.address2,"MIG44-16/98 BBA COLO jigolo")
        country=self.wait.until(EC.presence_of_element_located(self.country))
        select4=Select(country)
        select4.select_by_visible_text("Australia")
        self.type(self.state,"odisha")
        self.type(self.city,"bbsr")
        self.type(self.zip_code,"123415")
        self.type(self.NUMBER,"787945571")
        self.click(self.create_acnt)
